version: "3.3"
services:
  owtf:
    restart: always
    build: .
    command: owtf-cli
    environment:
      - DOCKER=True
      - POSTGRES_USER=owtf_db_user
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=owtf_db
    env_file:
      - owtf.env
    ports:
      - 8080:8080
      - 8010:8010
      - 8009:8009
    depends_on:
      - db
    volumes:
      - .:/owtf
  db:
    image: postgres:alpine
    ports:
      - 5342:5432
    environment:
      - POSTGRES_USER=owtf_db_user
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=owtf_db
    env_file:
      - owtf.env
